[package]
name = "types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0"
molecule = { version = "0.7.2", default-features = false }
no-std-compat = { version = "0.4.1", features = [ "alloc" ] }

serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0.96", default-features = false,  features = ["alloc"] }