[[cells]]
name = "sample-dapp"
enable_type_id = true

  [cells.location]
  file = "build/release/sample-dapp"

[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0x6cd8ae51f91bacd7910126f880138b30ac5d3015"
hash_type = "type"
