version: '3'
services:
  mvpdapp:
    image: ckbjs/kuai-mvp-dapp:latest
    restart: always
    network_mode: 'host'
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - REDIS_PORT=6379
      - REDIS_HOST=127.0.0.1

  redis:
    image: redis:latest
    restart: always
    network_mode: 'host'
