name: Release draft

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # for creating release
    env:
      IS_RC_MERGED: ${{ github.event.pull_requst.merged == true && startsWith(github.head_ref, 'rc/v')}}
    steps:
      - name: Create a release draft
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
