name: Test
on: [push, pull_request]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: restore lerna
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install project dependencies and build
        run: npm i

      - name: Build packages
        run: npm run build

      - name: Run test with coverage
        run: npx lerna run test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
